# -*- coding: utf-8 -*-
"""portafolio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kKnKGiSw8QyjlPHyG3BWhSvHILqtqRji
"""

import streamlit as st
import yfinance as yf
import numpy as np
import pandas as pd
from scipy.optimize import minimize

st.title("Optimizador de Portafolio - Markowitz")

st.write("Selecciona entre 2 y 10 activos y calcula el portafolio óptimo.")

# número de activos
n_assets = st.slider("Número de acciones", 2, 10, 3)

tickers = []

for i in range(n_assets):
    ticker = st.text_input(f"Ticker {i+1}")
    if ticker:
        tickers.append(ticker.upper())

target_return = st.slider(
    "Retorno objetivo anual",
    0.01,
    0.50,
    0.15
)

if st.button("Optimizar portafolio"):

    if len(tickers) < 2:
        st.warning("Ingresa al menos 2 tickers")
        st.stop()

    st.write("Descargando datos...")

    prices = yf.download(tickers, start="2022-01-01")["Close"]

    returns = prices.pct_change().dropna()

    mean_returns = returns.mean() * 252
    cov_matrix = returns.cov() * 252

    n = len(mean_returns)

    def portfolio_variance(weights):
        return np.dot(weights.T, np.dot(cov_matrix, weights))

    constraints = (
        {"type": "eq", "fun": lambda x: np.sum(x) - 1},
        {"type": "eq", "fun": lambda x: np.dot(x, mean_returns) - target_return}
    )

    bounds = tuple((0,1) for _ in range(n))

    init_guess = n * [1/n]

    result = minimize(
        portfolio_variance,
        init_guess,
        method="SLSQP",
        bounds=bounds,
        constraints=constraints
    )

    weights = result.x

    portfolio = pd.DataFrame({
        "Activo": tickers,
        "Peso": weights,
        "Peso %": weights * 100
    })

    st.subheader("Pesos óptimos (Markowitz)")

    st.dataframe(portfolio)

    st.bar_chart(portfolio.set_index("Activo")["Peso %"])

    portfolio_return = np.dot(weights, mean_returns)
    portfolio_vol = np.sqrt(portfolio_variance(weights))

    st.subheader("Métricas del portafolio")

    st.write("Retorno esperado anual:", round(portfolio_return,4))
    st.write("Volatilidad anual:", round(portfolio_vol,4))
